### ISSUE TITLE
Combat

### ISSUE THREAD

**Issue by karljlia** [mortnord/Steppe_Project#9]
Game crash when trying to use card nr. 4

File "C:\Users\karlj\PycharmProjects\Steppe_Project\Commands_Dirc\Combat.py", line 58, in player_use_card_round
    Static_Data.get_deck_list().hand[use_card_nr].dwarfs_required:
IndexError: list index out of range

**Comment by karljlia** [comment]
Working hard on it. Still no solution :(

**Comment by ChinoCodeDemon** [comment]
Where is hand created?
What should happen if the input is higher or lower than the expected range?

**Comment by mortnord** [comment]
irrelevant nå dessverre :P
